# Changes here will be overwritten by Copier
_commit: v0.0.2-dev1-4-g3901171
_src_path: https://github.com/UpDryTwist/stock-python-template.git
author_email: tathamg@gmail.com
author_name: UpDryTwist
docker_project: trmnl-tides
project_description: TRMNL Tides service for generating a TRMNL screen with local
    tides data.
project_name: TRMNL Tides
project_slug: trmnl_tides
python_package: trmnl_tides
python_package_command_line_name: trmnl-tides
python_version: '3.11'
repository_name: trmnl-tides
