[lint]

ignore = [
    "E501", # Line too long
    "D203", # 1 blank line required before class docstring
    "D212", # Multi-line docstring should start on 1st line
    "D413", # Missing blank line after last section (in multi-line docstrings)
    "ISC001",  # Concatentate strings on same line
]

select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # Warnings
    "W",
    # McCabe
    "C90",
    # Naming
    "N",
    # PyDocStyle
    "D",
    # Flake8-2020 - misuse of sys.version
    "YTT",
    # Flake8-Annotations
    "ANN",
    # Flake8-Async
    "ASYNC",
    # Flake8-Bandit
    "S",
    # Flake8-blind-except
    "BLE",
    # Flake8-boolean-trap
    "FBT",
    # Flake8-Builtins
    "A",
    # Flake8-copyright - in preview as of 12/24
    # "CPY",
    # Flake8-comprehensions
    "C4",
    # Flake8-datetimez
    "DTZ",
    # Flake8-debugger
    "T10",
    # Flake8-Django
    "DJ",
    # Flake8-errmsg
    "EM",
    # Flake8-executable
    "EXE",
    # Flake8-future-annotations
    "FA",
    # Flake8-implicit-str-concat
    "ISC",
    # Flake8-import-conventions
    "ICN",
    # Flake8-logging
    "LOG",
    # Flake8-logging-format
    "G",
    # Flake8-no-0pep420
    "INP",
    # Flake8-pie
    "PIE",
    # Flake8-print
    "T20",
    # Flake8-pyi
    "PYI",
    # Flake8-pytest-style
    "PT",
    # Flake8-quotes
    "Q",
    # Flake8-raise
    "RSE",
    # Flake8-return
    "RET",
    # Flake8-self
    "SLF",
    # Flake8-slots
    "SLOT",
    # Flake8-tidy-imports
    "TID",
    # Flake8-type-checking
    "TC",
    # Flake8-gettext
    "INT",
    # Flake8-unused-arguments
    "ARG",
    # Flake8-use-pathlib - nah, os.path is fine
    # "PTH",
    # Flake8-todos
    "TD",
    # Flake8-fixme
    "FIX",
    # Flake8-pandas-vet
    "PD",
    # Flake8-pygrep-hooks
    "PGH",
    # PyLint
    "PL",
    # tryceratops
    "TRY",
    # Flynt
    "FLY",
    # Perflint
    "PERF",
    # Refurb
    "FURB",
    # pydoclint - in preview as of 12/24
    # "DOC",
    # Ruff-specific
    "RUF",
]
